apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupiterapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupiterapp
  template:
    metadata:
      labels:
        app: jupiterapp
    spec:
      containers:
        - name: jupitercontainer
          image: elvdocker/jupiter-app
          resources:
            requests:
              memory: 150Mi
              cpu: 300m
            limits:
              memory: 512Mi
              cpu: 1000m
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: jupiterapp
spec:
  selector:
    app: jupiterapp
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80




  
